ARG NODE_VERSION=24-alpine
ARG EXPO_PUBLIC_ENV=dev

FROM node:${NODE_VERSION} AS builder
WORKDIR /app

ENV EXPO_PUBLIC_ENV=${EXPO_PUBLIC_ENV}

COPY package.json package-lock.json ./
COPY types-party-battle types-party-battle
COPY frontend-party-battle frontend-party-battle
RUN npm ci --workspace types-party-battle --workspace frontend-party-battle --include-workspace-root=false

RUN npm run -w types-party-battle build

WORKDIR /app/frontend-party-battle
RUN npx expo export -p web

FROM nginx:stable-alpine

COPY frontend-party-battle/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/frontend-party-battle/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
