name: ci

on:
  pull_request:
    branches: [main]

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build shared types
        run: npm run -w types-party-battle build

      - name: Run linting for CI
        run: npm run lint:ci
        continue-on-error: true

      - name: Run tests for CI
        run: npm run test:ci
        continue-on-error: true

      - name: Publish test results
        uses: dorny/test-reporter@v1
        with:
          name: Test Results
          path: |
            backend-party-battle/test-results.json
          reporter: mocha-json
          fail-on-error: true

      - name: Publish lint results
        uses: dorny/test-reporter@v1
        with:
          name: Lint Results
          path: |
            backend-party-battle/lint-results.xml
            frontend-party-battle/lint-results.xml
            types-party-battle/lint-results.xml
          reporter: java-junit
          fail-on-error: true
