name: CI

on:
  pull_request:
    branches: [main]

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build shared types
        run: npm run -w types-party-battle build

      - name: Run linting for CI
        run: npm run lint:ci

      - name: Run tests for CI
        run: npm run test:ci

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Results
          path: '**/test-results.json'
          reporter: mocha-json
          fail-on-error: true

      - name: Publish lint results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Lint Results
          path: '**/lint-results.xml'
          reporter: java-junit
          fail-on-error: true
