name: release

on:
  push:
    branches:
    - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    outputs:
      paths: ${{ steps.rp.outputs.paths_released }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: rp
        with:
          token: ${{ secrets.GH_PAT_RELEASE_PLEASE }}

  build-backend:
    needs: release
    if: contains(join(fromJSON(needs.release.outputs.paths), ','), 'backend-party-battle')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_VERSION: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
        id: buildx

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: ./backend-party-battle
          file: ./backend-party-battle/dockerfile
          push: true
          tags: |
            ghcr.io/thirty-degrees/backend-party-battle:${{ env.IMAGE_VERSION }}
            ghcr.io/thirty-degrees/backend-party-battle:latest
          build-args: |
            VERSION=alpine
          platforms: linux/arm64
          cache-from: type=registry,ref=ghcr.io/thirty-degrees/backend-party-battle:buildcache
          cache-to: type=registry,ref=ghcr.io/thirty-degrees/backend-party-battle:buildcache,mode=max

  build-web:
    needs: release
    if: contains(join(fromJSON(needs.release.outputs.paths), ','), 'frontend-party-battle')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_VERSION: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
        id: buildx

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: ./frontend-party-battle
          file: ./frontend-party-battle/dockerfile
          push: true
          tags: |
            ghcr.io/thirty-degrees/frontend-party-battle-web:${{ env.IMAGE_VERSION }}
            ghcr.io/thirty-degrees/frontend-party-battle-web:latest
          platforms: linux/arm64
          cache-from: type=registry,ref=ghcr.io/thirty-degrees/frontend-party-battle-web:buildcache
          cache-to: type=registry,ref=ghcr.io/thirty-degrees/frontend-party-battle-web:buildcache,mode=max
