name: release

on:
  push:
    branches:
    - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    outputs:
      paths: ${{ steps.rp.outputs.paths_released }}
      releases: ${{ steps.rp.outputs.releases_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: rp
        with:
          token: ${{ secrets.GH_PAT_RELEASE_PLEASE }}

  build-backend:
    needs: release
    if: contains(join(fromJSON(needs.release.outputs.paths), ','), 'backend-party-battle')
    runs-on: blacksmith-4vcpu-ubuntu-2404-arm
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_VERSION: ${{ github.sha }}
    outputs:
      image_version: ${{ env.IMAGE_VERSION }}
      backend_version: ${{ steps.derive_backend_version.outputs.backend_version }}
    steps:
      - uses: actions/checkout@v4

      - name: Derive backend version from release outputs
        id: derive_backend_version
        env:
          RELEASES: ${{ needs.release.outputs.releases }}
        run: |
          chmod +x .github/scripts/read_manifest_version.py
          ver=$(.github/scripts/read_manifest_version.py backend-party-battle)
          echo "BACKEND_VERSION=$ver" >> $GITHUB_ENV
          echo "backend_version=$ver" >> $GITHUB_OUTPUT

      - name: Setup Blacksmith Builder
        uses: useblacksmith/setup-docker-builder@v1

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: useblacksmith/build-push-action@v2
        with:
          context: ./backend-party-battle
          file: ./backend-party-battle/dockerfile
          push: true
          tags: |
            ghcr.io/thirty-degrees/backend-party-battle:${{ env.IMAGE_VERSION }}
            ghcr.io/thirty-degrees/backend-party-battle:latest
          build-args: |
            VERSION=alpine
          platforms: linux/arm64
          cache-from: type=registry,ref=ghcr.io/thirty-degrees/backend-party-battle:buildcache
          cache-to: type=registry,ref=ghcr.io/thirty-degrees/backend-party-battle:buildcache,mode=max

  trigger-backend-deployment:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - name: Trigger backend image update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT_ACTIONS_TRIGGER }}
          repository: Calfur/calfur-dev
          event-type: add-party-battle-backend-version
          client-payload: '{"image_version":"${{ needs.build-backend.outputs.image_version }}","backend_version":"${{ needs.build-backend.outputs.backend_version }}"}'

  build-web:
    needs: release
    if: contains(join(fromJSON(needs.release.outputs.paths), ','), 'frontend-party-battle')
    runs-on: blacksmith-4vcpu-ubuntu-2404-arm
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_VERSION: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Blacksmith Builder
        uses: useblacksmith/setup-docker-builder@v1

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: useblacksmith/build-push-action@v2
        with:
          context: ./frontend-party-battle
          file: ./frontend-party-battle/dockerfile
          push: true
          tags: |
            ghcr.io/thirty-degrees/frontend-party-battle-web:${{ env.IMAGE_VERSION }}
            ghcr.io/thirty-degrees/frontend-party-battle-web:latest
          platforms: linux/arm64
          cache-from: type=registry,ref=ghcr.io/thirty-degrees/frontend-party-battle-web:buildcache
          cache-to: type=registry,ref=ghcr.io/thirty-degrees/frontend-party-battle-web:buildcache,mode=max

  build-android:
    needs: release
    if: contains(join(fromJSON(needs.release.outputs.paths), ','), 'frontend-party-battle')
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android build tools
        run: sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Install dependencies
        working-directory: ./frontend-party-battle
        run: npm ci

      - name: Configure Google Service Account
        working-directory: ./frontend-party-battle
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: echo "$GOOGLE_SERVICE_ACCOUNT_JSON" > service-account.json

      - name: Prebuild native Android project
        working-directory: ./frontend-party-battle
        run: npx expo prebuild --platform android --non-interactive --clean

      - name: Decode Android keystore
        working-directory: ./frontend-party-battle
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          mkdir -p android/app
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/keystore.jks

      - name: Build Android AAB with Gradle
        working-directory: ./frontend-party-battle/android
        run: ./gradlew bundleRelease

      - name: Sign Android AAB
        working-directory: ./frontend-party-battle
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          jarsigner \
            -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore android/app/keystore.jks \
            -storepass "$ANDROID_KEYSTORE_PASSWORD" \
            -keypass "$ANDROID_KEY_PASSWORD" \
            android/app/build/outputs/bundle/release/app-release.aab \
            "$ANDROID_KEY_ALIAS"

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: frontend-party-battle/service-account.json
          packageName: ch.thirty_degrees.party_battle
          releaseFiles: frontend-party-battle/android/app/build/outputs/bundle/release/app-release.aab
          track: internal
