name: release

on:
  push:
    branches:
    - main

jobs:
  release:
    runs-on: blacksmith-4vcpu-ubuntu-2404-arm
    permissions:
      contents: write
      pull-requests: write
      issues: write
    outputs:
      paths: ${{ steps.rp.outputs.paths_released }}
      releases: ${{ steps.rp.outputs.releases_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: rp
        with:
          token: ${{ secrets.GH_PAT_RELEASE_PLEASE }}

  build-backend:
    needs: release
    if: contains(join(fromJSON(needs.release.outputs.paths), ','), 'backend-party-battle')
    runs-on: blacksmith-4vcpu-ubuntu-2404-arm
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_VERSION: ${{ github.sha }}
    outputs:
      image_version: ${{ env.IMAGE_VERSION }}
      backend_version: ${{ steps.derive_backend_version.outputs.backend_version }}
    steps:
      - uses: actions/checkout@v4

      - name: Derive backend version from release outputs
        id: derive_backend_version
        env:
          RELEASES: ${{ needs.release.outputs.releases }}
        run: |
          chmod +x .github/scripts/read_manifest_version.py
          ver=$(.github/scripts/read_manifest_version.py backend-party-battle)
          echo "BACKEND_VERSION=$ver" >> $GITHUB_ENV
          echo "backend_version=$ver" >> $GITHUB_OUTPUT

      - name: Setup Blacksmith Builder
        uses: useblacksmith/setup-docker-builder@v1

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: useblacksmith/build-push-action@v2
        with:
          context: ./backend-party-battle
          file: ./backend-party-battle/dockerfile
          push: true
          tags: |
            ghcr.io/thirty-degrees/backend-party-battle:${{ env.IMAGE_VERSION }}
            ghcr.io/thirty-degrees/backend-party-battle:latest
          build-args: |
            VERSION=alpine
          platforms: linux/arm64
          cache-from: type=registry,ref=ghcr.io/thirty-degrees/backend-party-battle:buildcache
          cache-to: type=registry,ref=ghcr.io/thirty-degrees/backend-party-battle:buildcache,mode=max

  trigger-backend-deployment:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - name: Trigger backend image update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT_ACTIONS_TRIGGER }}
          repository: Calfur/calfur-dev
          event-type: add-party-battle-backend-version
          client-payload: '{"image_version":"${{ needs.build-backend.outputs.image_version }}","backend_version":"${{ needs.build-backend.outputs.backend_version }}"}'

  build-web:
    needs: release
    if: contains(join(fromJSON(needs.release.outputs.paths), ','), 'frontend-party-battle')
    runs-on: blacksmith-4vcpu-ubuntu-2404-arm
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_VERSION: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Blacksmith Builder
        uses: useblacksmith/setup-docker-builder@v1

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: useblacksmith/build-push-action@v2
        with:
          context: ./frontend-party-battle
          file: ./frontend-party-battle/dockerfile
          push: true
          tags: |
            ghcr.io/thirty-degrees/frontend-party-battle-web:${{ env.IMAGE_VERSION }}
            ghcr.io/thirty-degrees/frontend-party-battle-web:latest
          platforms: linux/arm64
          cache-from: type=registry,ref=ghcr.io/thirty-degrees/frontend-party-battle-web:buildcache
          cache-to: type=registry,ref=ghcr.io/thirty-degrees/frontend-party-battle-web:buildcache,mode=max
